CREATE TABLE WORKER (
	W_ID INT PRIMARY KEY,
    F_NAME VARCHAR(50),
    L_NAME VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(100)
);

INSERT INTO WORKER
	VALUES
    (102, "SAHIL", "KHAN", "KANPUR", "UTTAR PRADESH"),
    (104, "SAMEER", "PRIKH", "ROOP NAGAR", "PUNJAB"),
    (105, "MARY", "JONES", "DELHI", "DELHI"),
    (106, "MAHIR", "SHARMA", "SONIPAT", "HARYANAYA"),
    (107, "ATHARVA", "BHARDWAJ", "DELHI", "DELHI"),
    (108, "VEDA", "SHARMA", "KANPUR", "UTTAR PRADESH");
    
SELECT F_NAME, CITY
FROM WORKER
ORDER BY STATE DESC;

SELECT DISTINCT(CITY) FROM WORKER;

SELECT F_NAME, STATE 
FROM WORKER 
WHERE L_NAME LIKE '_HA%';

SELECT CITY, COUNT(*)
FROM WORKER
GROUP BY CITY;


CREATE TABLE WORKER (
	W_ID INT PRIMARY KEY,
    F_NAME VARCHAR(50),
    L_NAME VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(100)
);

INSERT INTO WORKER
(W_ID, F_NAME, L_NAME, CITY, STATE)
	VALUES
    (102, "SAHIL", "KHAN", "KANPUR", "UTTAR PRADESH"),
    (104, "SAMEER", "PRIKH", "ROOP NAGAR", "PUNJAB"),
    (105, "MARY", "JONES", "DELHI", "DELHI"),
    (106, "MAHIR", "SHARMA", "SONIPAT", "HARYANAYA"),
    (107, "ATHARVA", "BHARDWAJ", "DELHI", "DELHI"),
    (108, "VEDA", "SHARMA", "KANPUR", "UTTAR PRADESH");
    
SELECT F_NAME, CITY
FROM WORKER
ORDER BY STATE DESC;

SELECT DISTINCT(CITY) FROM WORKER;

SELECT F_NAME, STATE 
FROM WORKER 
WHERE L_NAME LIKE '_HA%';

SELECT CITY, COUNT(*)
FROM WORKER
GROUP BY CITY;

CREATE TABLE COMPUTER (
	PROD_ID CHAR(4) PRIMARY KEY,
    PROD_NAME VARCHAR(50),
    PRICE INT,
    COMPANY VARCHAR(50),
    TYPE VARCHAR(50)
);

INSERT INTO COMPUTER
(PROD_ID, PROD_NAME, PRICE, COMPANY, TYPE)
VALUES
("P001", "MOUSE", 200, "LOGITECH", "INPUT"),
("P002", "LASER PRINTER", 4000, "CANON", "OUTPUT"),
("P003", "KEYBOARD", 500, "LOGITECH", "INPUT"),
("P004", "JOYSTICK", 1000, "IBALL", "INPUT"),
("P005", "SPEAKER", 1200, "CREATIVE", "OUTPUT"),
("P006", "DSKJET PRINTER", 4300, "CANON", "OUTPUT");

CREATE TABLE SALES (
	PROD_ID CHAR(5),
    QTY_SOLD INT,
    QUARTER INT
);

INSERT INTO SALES
(PROD_ID, QTY_SOLD, QUARTER)
VALUES
("P002", 4, 1),
("P003", 2, 2),
("P001", 3, 2),
("P004", 2, 1);

SELECT MIN(PRICE), MAX(PRICE) FROM COMPUTER;

SELECT COMPANY, COUNT(*) FROM COMPUTER GROUP BY COMPANY HAVING COUNT(COMPANY) > 1;

SELECT PROD_NAME, QTY_SOLD 
FROM COMPUTER C, SALES S 
WHERE C.PROD_ID = S.PROD_ID AND TYPE = 'INPUT';

SELECT PROD_NAME, COMPANY, QUARTER 
FROM COMPUTER C, SALES S 
WHERE C.PROD_ID = S.PROD_ID;